version: "3.5"

services:
  netric:
    image: dockerhub.aereus.com/www_hannahstebnicki_com:${APPLICATION_VER}
    environment:
      APP_ENV: ${APPLICATION_ENV}
      APP_VER: ${APPLICATION_VER}
    ports:
      - 10006:3000
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role!=manager
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first
